export default {
  Box: require('../Img/Box.png'),
  Logo: require('../Img/Logo.png'),
  Plus: require('../Img/Plus.png'),
  Doctor: require('../Img/Doctor.png'),
  Girl: require('../Img/Menina.png'),
  Boy: require('../Img/Menino.png'),
  Google: require('../Img/google.png'),
  boxoff: require('../Img/boxoff.png'),
  boxon: require('../Img/boxon.png'),
  dayoff: require('../Img/dayoff.png'),
  dayon: require('../Img/dayon.png'),
  scheduleoff: require('../Img/scheduleoff.png'),
  scheduleon: require('../Img/scheduleon.png'),
  girlInvert: require('../Img/girlInvert.png'),
};
